### ISSUE TITLE
Firewall settings prevent remote connection to MariaDB by default.

### ISSUE THREAD

**Issue by creitve** [simtechdev/smtk-devbox#8]
Shouldn't the port be open by default? Or is it a security matter?

**Comment by gongled** [comment]
Fixed (https://github.com/simtechdev/smtk-devbox/commit/0204f0abe25f826ac9d98cd0123fd18ea7a0ef4c). Could you have a look on this fix on `develop` branch?

**Comment by gongled** [comment]
I've checked this issue for you – 3306/tcp is open on firewall. Anyway, by default you can't connect to MySQL database because of absence of permissions for outside connections. As a workaround you should grant permissions manually (connect to MySQL inside of your VM and execute `grant all privileges on *.* to 'root'@'%' identified by 'password'`) or use SSH tunneling for connections to MySQL.

**Comment by gongled** [comment]
On the other hand in some cases it might be useful. Fixed this issue (421e93c018fabad03e4638e2e640f61b40eacfbc).
